baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Graham's Super Website"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Graham's website"
    weight = 1
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "/images/logo.png"
  description = "Get a super slick website"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-purple"
  recent_posts_number = 3
  read_more_copy = "Read more about this entry"

# [[params.ananke_socials]]
# name = "github"
# url = "https://github.com/theNewDynamic"
